---

# RabbitMQ official install
- name: "add the official rabbitmq repository's key"
  apt_key: url=https://www.rabbitmq.com/rabbitmq-signing-key-public.asc
  when: not rabbitmq_os_package

- name: add the official rabbitmq repository
  copy:
    src=../../files/rabbitmq.list
    dest=/etc/apt/sources.list.d/
    backup=yes
  register: aptrepo
  when: not rabbitmq_os_package

- name: install rabbitmq-server
  apt: name=rabbitmq-server update_cache=yes

- name: enable rabbitmq-server to survive reboot
  service: name=rabbitmq-server enabled=yes
