---
- include: etc.yml
  tags: [setup]

- include: mysql.yml
  tags: [setup, mysql]

- include: apache.yml
  tags: [setup]

- include: vagrant.yml
  tags: [setup]

- include: node.yml
  tags: [setup]

- include: ruby.yml
  tags: [setup]

- include: python.yml
  tags: [setup]

- include: django.yml
  tags: [app]
