version: '2'
services:
  noext:
    #run tests with no external dependencies 
    image: quay.io/mozmar/kuma_base
    volumes:
      - ./:/app
    command: py.test --nomigrations kuma/humans kuma/spam
    environment:
      - DATABASE_URL=sqlite:///
      - PYTHONDONTWRITEBYTECODE=1

  sqlite_memcached:
    #memcached only external dependency
    #many tests currently fail due to dependency on mysql specific behavior
    image: quay.io/mozmar/kuma_base
    volumes:
      - ./:/app
    command: py.test --nomigrations kuma --ignore=kuma/search
    depends_on:
      - memcached
    environment:
      - DATABASE_URL=sqlite:///
      - MEMCACHE_SERVERS=memcached:11211
      - PYTHONDONTWRITEBYTECODE=1

  nosearch:
    image: quay.io/mozmar/kuma_base
    volumes:
      - ./:/app
    command: py.test --nomigrations kuma --ignore=kuma/search
    depends_on:
      - memcached
      - mysql
    environment:
      - DATABASE_URL=mysql://root:kuma@mysql:3306/developer_mozilla_org
      - MEMCACHE_SERVERS=memcached:11211
      - PYTHONDONTWRITEBYTECODE=1

  test:
    image: quay.io/mozmar/kuma_base
    volumes:
      - ./:/app
    command: py.test --nomigrations kuma
    depends_on:
      - memcached
      - mysql
      - elasticsearch
    environment:
      - DATABASE_URL=mysql://root:kuma@mysql:3306/developer_mozilla_org
      - ES_URLS=elasticsearch:9200
      - MEMCACHE_SERVERS=memcached:11211
      - PYTHONDONTWRITEBYTECODE=1
