---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define apache_packages.
  set_fact:
    apache_packages: "{{ __apache_packages | list }}"
  when: apache_packages is not defined

# Setup/install tasks.
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

# Figure out what version of Apache is installed.
- name: Get installed version of Apache.
  command: "{{ apache_daemon }} -v"
  changed_when: false
  register: _apache_version

- name: Create apache_version variable.
  set_fact:
    apache_version: "{{ _apache_version.stdout.split()[2].split('/')[1] }}"

- include_vars: apache-22.yml
  when: "apache_version.split('.')[1] == '2'"

- include_vars: apache-24.yml
  when: "apache_version.split('.')[1] == '4'"

# Configure Apache.
- include: configure-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: configure-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Ensure Apache is started and enabled on boot.
  service:
    name: "{{ apache_daemon }}"
    state: started
    enabled: yes
