name: JavaScript and SASS Lints

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: technote-space/get-diff-action@v3
        id: git_diff_content
        with:
          SUFFIX_FILTER: |
            .js
            .jsx
            .scss
          PREFIX_FILTER: kuma
          FILES: |
            package.json
            yarn.lock

      - name: Setup Node.js environment
        if: steps.git_diff_content.outputs.diff
        uses: actions/setup-node@v2-beta
        with:
          node-version: "12"

      - name: Get yarn cache directory path
        if: steps.git_diff_content.outputs.diff
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2.1.5
        if: steps.git_diff_content.outputs.diff
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Yarn install
        if: steps.git_diff_content.outputs.diff
        run: yarn install --frozen-lockfile

      - name: Linting
        if: steps.git_diff_content.outputs.diff
        run: |
          yarn run eslint
          yarn run stylelint
          yarn run pretty

      - name: Flow
        if: steps.git_diff_content.outputs.diff
        run: |
          yarn run flow
